### ISSUE TITLE
Accounts DB Creation Issue

### ISSUE THREAD

**Issue by hack13** [s5-dev/S5#21]
So when trying to initialize application for the first time it launches just fine and is accessible generating the seed and all, but when you attempt to add the [accounts] and [accounts.database] it appears to fail to create it, and stops the application from fully launching.

I have attempted to use the path in the docs and a unique path for (one not inside the /db directory) neither results in a change. Here is the log output.

**Config Section**
```toml
[accounts]
enabled = true
alwaysAllowedScopes = [
    'account/login',
    'account/register',
    's5/registry/read',
    's5/metadata',
    's5/debug/storage_locations',
    's5/debug/download_urls',
    's5/blob/redirect',
]
[accounts.database]
path = "/accounts"
```

**SQLite Error on Boot**
```
s5box-s5-node-1  | [sqlite] init
s5box-s5-node-1  | 2023-09-07 14:13:19.093995 - info - HTTP Server listening on port 8989
s5box-s5-node-1  | [cache] total used cache size: 0 B / 4 GB
s5box-s5-node-1  | [cache] doing nothing because max cache size is not reached yet
s5box-s5-node-1  | [warn] SqfliteFfiException(error, Invalid argument(s): Failed to load dynamic library 'libsqlite3.so': libsqlite3.so: cannot open shared object file: No such file or directory}) DatabaseException(Invalid argument(s): Failed to load dynamic library 'libsqlite3.so': libsqlite3.so: cannot open shared object file: No such file or directory)
s5box-s5-node-1  | #0      responseToResultOrThrow (package:sqflite_common_ffi/src/method_call.dart:123)
s5box-s5-node-1  | #1      SqfliteIsolate.handle (package:sqflite_common_ffi/src/isolate.dart:33)
s5box-s5-node-1  | <asynchronous suspension>
s5box-s5-node-1  | #2      _isolateHandle (package:sqflite_common_ffi/src/database_factory_ffi_io.dart:94)
s5box-s5-node-1  | <asynchronous suspension>
s5box-s5-node-1  | #3      ffiMethodCallhandleInIsolate (package:sqflite_common_ffi/src/database_factory_ffi_io.dart:49)
s5box-s5-node-1  | <asynchronous suspension>
s5box-s5-node-1  | #4      _SqfliteDatabaseFactoryImpl.invokeMethod (package:sqflite_common/src/mixin/factory.dart:22)
s5box-s5-node-1  | <asynchronous suspension>
s5box-s5-node-1  | #5      SqfliteDatabaseMixin.openDatabase (package:sqflite_common/src/database_mixin.dart:777)
s5box-s5-node-1  | <asynchronous suspension>
s5box-s5-node-1  | #6      SqfliteDatabaseMixin.doOpen (package:sqflite_common/src/database_mixin.dart:879)
s5box-s5-node-1  | <asynchronous suspension>
s5box-s5-node-1  | #7      SqfliteDatabaseOpenHelper.openDatabase (package:sqflite_common/src/database.dart:46)
s5box-s5-node-1  | <asynchronous suspension>
s5box-s5-node-1  | #8      SqfliteDatabaseFactoryMixin.openDatabase.<anonymous closure> (package:sqflite_common/src/factory_mixin.dart:110)
s5box-s5-node-1  | <asynchronous suspension>
s5box-s5-node-1  | #9      ReentrantLock.synchronized.<anonymous closure> (package:synchronized/src/reentrant_lock.dart:37)
s5box-s5-node-1  | <asynchronous suspension>
s5box-s5-node-1  | #10     BasicLock.synchronized (package:synchronized/src/basic_lock.dart:33)
s5box-s5-node-1  | <asynchronous suspension>
s5box-s5-node-1  | #11     SQLService.init (package:s5_server/service/sql.dart:22)
s5box-s5-node-1  | <asynchronous suspension>
s5box-s5-node-1  | #12     AccountsService.init (package:s5_server/service/accounts.dart:197)
s5box-s5-node-1  | <asynchronous suspension>
s5box-s5-node-1  | #13     S5Node.start (package:s5_server/node.dart:146)
s5box-s5-node-1  | <asynchronous suspension>
```

**Comment by redsolver** [comment]
I just published https://github.com/s5-dev/S5/releases/tag/v0.13.3 which should fix this. The new Docker image with the fix should be available in about 40 minutes. Please let me know if the new image fixes it, thanks

**Comment by hack13** [comment]
I can confirm this did resolve the issue
